name: CI Workflow

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - master
      - release
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FULL_NAME: "Такиуллин Тимур Ирекович"
      GROUP_NUMBER: "M3116"
      GITHUB_USERNAME: "Takiullin Timur"

    steps:
      - name: Вывод информации
        run: |
          echo "ФИО: $FULL_NAME"
          echo "Номер группы: $GROUP_NUMBER"
          echo "Ник на GitHub: $GITHUB_USERNAME"

      - name: Установка Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Запуск юнит-тестов
        run: |
          python -m unittest discover

      - name: Проверка кода на стиль
        run: |
          pip install flake8
          flake8 .
          
      - name: Форматирование кода
        run: |
          pip install black
          black .
